{
  "id": "CVE-2014-1624",
  "definition_id": "oval:org.opensuse.security:def:20141624",
  "title": "CVE-2014-1624",
  "description": "\n    Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called.\n    ",
  "cvss3": "4/CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
  "severity": "Low",
  "impact": "low",
  "affected": {
    "family": "unix",
    "platforms": [
      "SUSE Linux Enterprise Desktop 12",
      "SUSE Linux Enterprise Desktop 12 SP4"
    ],
    "cpes": [
      "cpe:/o:suse:sled:12",
      "cpe:/o:suse:sled:12:sp4"
    ]
  },
  "packages": [
    {
      "name": "python-xdg",
      "status": "not-affected",
      "platform": "SUSE Linux Enterprise Desktop 12"
    }
  ],
  "references": [
    {
      "id": "Mitre CVE-2014-1624",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1624"
    },
    {
      "id": "SUSE CVE-2014-1624",
      "source": "SUSE CVE",
      "url": "https://www.suse.com/security/cve/CVE-2014-1624"
    },
    {
      "id": "SUSE-SU-2019:2719-1",
      "source": "SUSE-SU",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2019-October/006030.html"
    },
    {
      "id": "SUSE-SU-2019:2719-2",
      "source": "SUSE-SU",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2019-November/006123.html"
    },
    {
      "id": "SUSE bug 859835",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/859835"
    }
  ],
  "issued": "2021-04-30T00:00:00Z",
  "updated": "2022-03-01T00:00:00Z"
}
