{
  "id": "CVE-2019-20477",
  "definition_id": "oval:org.opensuse.security:def:201920477",
  "title": "CVE-2019-20477",
  "description": "\n    PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.\n    ",
  "severity": "Important",
  "impact": "important",
  "affected": {
    "family": "unix",
    "platforms": [
      "SUSE Linux Enterprise Desktop 15",
      "SUSE Linux Enterprise Desktop 15 SP1",
      "SUSE Linux Enterprise High Performance Computing 15",
      "SUSE Linux Enterprise High Performance Computing 15 SP1",
      "SUSE Linux Enterprise Module for Basesystem 15",
      "SUSE Linux Enterprise Module for Basesystem 15 SP1",
      "SUSE Linux Enterprise Module for Python 2 15 SP1",
      "SUSE Linux Enterprise Server 15",
      "SUSE Linux Enterprise Server 15 SP1",
      "SUSE Linux Enterprise Server for SAP Applications 15",
      "SUSE Linux Enterprise Server for SAP Applications 15 SP1",
      "SUSE Linux Enterprise Storage 6",
      "SUSE Manager Proxy 4.0",
      "SUSE Manager Retail Branch Server 4.0",
      "SUSE Manager Server 4.0"
    ],
    "cpes": [
      "cpe:/o:suse:ses:6",
      "cpe:/o:suse:sle-module-basesystem:15",
      "cpe:/o:suse:sle-module-basesystem:15:sp1",
      "cpe:/o:suse:sle-module-python2:15:sp1",
      "cpe:/o:suse:sle_hpc:15",
      "cpe:/o:suse:sle_hpc:15:sp1",
      "cpe:/o:suse:sled:15",
      "cpe:/o:suse:sled:15:sp1",
      "cpe:/o:suse:sles:15",
      "cpe:/o:suse:sles:15:sp1",
      "cpe:/o:suse:sles_sap:15",
      "cpe:/o:suse:sles_sap:15:sp1",
      "cpe:/o:suse:suse-manager-proxy:4.0",
      "cpe:/o:suse:suse-manager-retail-branch-server:4.0",
      "cpe:/o:suse:suse-manager-server:4.0"
    ]
  },
  "packages": [
    {
      "name": "python-PyYAML",
      "status": "not-affected",
      "platform": "SUSE Linux Enterprise Desktop 15 SP1"
    },
    {
      "name": "python-PyYAML",
      "status": "not-affected",
      "platform": "SUSE Linux Enterprise High Performance Computing 15 SP1"
    },
    {
      "name": "python-PyYAML",
      "status": "not-affected",
      "platform": "SUSE Linux Enterprise Module for Basesystem 15 SP1"
    },
    {
      "name": "python-PyYAML",
      "status": "not-affected",
      "platform": "SUSE Linux Enterprise Module for Python 2 15 SP1"
    },
    {
      "name": "python-PyYAML",
      "status": "not-affected",
      "platform": "SUSE Linux Enterprise Server 15 SP1"
    },
    {
      "name": "python-PyYAML",
      "status": "not-affected",
      "platform": "SUSE Linux Enterprise Server for SAP Applications 15 SP1"
    }
  ],
  "references": [
    {
      "id": "Mitre CVE-2019-20477",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-20477"
    },
    {
      "id": "SUSE CVE-2019-20477",
      "source": "SUSE CVE",
      "url": "https://www.suse.com/security/cve/CVE-2019-20477"
    },
    {
      "id": "SUSE bug 1164453",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1164453"
    }
  ],
  "issued": "2021-04-30T00:00:00Z",
  "updated": "2022-04-29T00:00:00Z"
}
