{
  "vulinfo_id": "JVNDB-2016-004527",
  "title": "CPython の smtplib ライブラリにおける TLS の保護を回避される脆弱性",
  "vulinfo_description": "CPython (別名 Python) の smtplib ライブラリは、StartTLS が失敗した際、エラーを返さないため、TLS の保護を回避される脆弱性が存在します。  本脆弱性は、\"StartTLS stripping 攻撃\" の脆弱性と呼ばれています。  補足情報 : CWE による脆弱性タイプは、CWE-693: Protection Mechanism Failure (保護メカニズムの不具合) と識別されています。 http://cwe.mitre.org/data/definitions/693.html",
  "affected": [
    {
      "name": "Python Software Foundation",
      "product_name": "Python",
      "version_number": [
        "2.7.12 未満",
        "3.4.5 未満の 3.x",
        "3.5.2 未満の 3.5.x"
      ],
      "cpe": {
        "version": "2.2",
        "text": "cpe:/a:python:python"
      }
    }
  ],
  "impact": {
    "cvss": [
      {
        "version": "2.0",
        "severity": {
          "type": "Base",
          "text": "Medium"
        },
        "base": "5.8",
        "vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N"
      },
      {
        "version": "3.0",
        "severity": {
          "type": "Base",
          "text": "Medium"
        },
        "base": "6.5",
        "vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:H/A:N"
      }
    ],
    "impact_item": "中間者攻撃 (man-in-the-middle attack) により、クライアントと StartTLS コマンドをブロックするためのレジストリ間のネットワークポジションを利用されることで、TLS の保護を回避される可能性があります。"
  },
  "solution": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。",
  "related": [
    {
      "type": "vendor",
      "name": "Changelog",
      "vulinfo_id": "Python 3.5.2",
      "url": "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2"
    },
    {
      "type": "vendor",
      "name": "Changelog",
      "vulinfo_id": "Python 3.4.5",
      "url": "https://docs.python.org/3.4/whatsnew/changelog.html#python-3-4-5"
    },
    {
      "type": "vendor",
      "name": "Python",
      "vulinfo_id": "changeset 101887:d590114c2394 3.4",
      "url": "https://hg.python.org/cpython/rev/d590114c2394"
    },
    {
      "type": "vendor",
      "name": "Python",
      "vulinfo_id": "changeset 101886:b3ce713fb9be 2.7",
      "url": "https://hg.python.org/cpython/rev/b3ce713fb9be"
    },
    {
      "type": "vendor",
      "name": "Python News",
      "vulinfo_id": "What's New in Python 2.7.12?",
      "url": "https://hg.python.org/cpython/raw-file/v2.7.12/Misc/NEWS"
    },
    {
      "type": "vendor",
      "name": "Red Hat Bugzilla",
      "vulinfo_id": "Bug 1303647",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1303647"
    },
    {
      "type": "advisory",
      "name": "Common Vulnerabilities and Exposures (CVE)",
      "vulinfo_id": "CVE-2016-0772",
      "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-0772"
    },
    {
      "type": "advisory",
      "name": "National Vulnerability Database (NVD)",
      "vulinfo_id": "CVE-2016-0772",
      "url": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-0772"
    },
    {
      "type": "cwe",
      "name": "JVNDB",
      "vulinfo_id": "CWE-Other",
      "url": "https://www.ipa.go.jp/security/vuln/CWE.html#CWEOther",
      "title": "その他"
    }
  ],
  "history": [
    {
      "history_no": "0",
      "date_time": "2018-02-17T01:37:52Z",
      "description": "[2016年09月05日]\\n  掲載"
    }
  ],
  "date_first_published": "2016-09-05T16:45:34+09:00",
  "date_last_updated": "2016-09-05T16:45:34+09:00",
  "date_public": "2016-06-25T00:00:00+09:00"
}
