{
  "id": "CVE-2008-3143",
  "definition_id": "oval:org.opensuse.security:def:20083143",
  "title": "CVE-2008-3143",
  "description": "\n    Multiple integer overflows in Python before 2.5.2 might allow context-dependent attackers to have an unknown impact via vectors related to (1) Include/pymem.h; (2) _csv.c, (3) _struct.c, (4) arraymodule.c, (5) audioop.c, (6) binascii.c, (7) cPickle.c, (8) cStringIO.c, (9) cjkcodecs/multibytecodec.c, (10) datetimemodule.c, (11) md5.c, (12) rgbimgmodule.c, and (13) stropmodule.c in Modules/; (14) bufferobject.c, (15) listobject.c, and (16) obmalloc.c in Objects/; (17) Parser/node.c; and (18) asdl.c, (19) ast.c, (20) bltinmodule.c, and (21) compile.c in Python/, as addressed by \"checks for integer overflows, contributed by Google.\"\n    ",
  "severity": "Moderate",
  "impact": "moderate",
  "affected": {
    "family": "unix",
    "platforms": [
      "SUSE Linux Enterprise Server 11 SP1",
      "SUSE Linux Enterprise Server 11 SP2",
      "SUSE Linux Enterprise Server 11 SP3",
      "SUSE Linux Enterprise Server 11 SP4"
    ],
    "cpes": [
      "cpe:/o:suse:suse_sles:11:sp1",
      "cpe:/o:suse:suse_sles:11:sp2",
      "cpe:/o:suse:suse_sles:11:sp3",
      "cpe:/o:suse:suse_sles:11:sp4"
    ]
  },
  "packages": [
    {
      "name": "python",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    },
    {
      "name": "python-32bit",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    },
    {
      "name": "python-curses",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    },
    {
      "name": "python-demo",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    },
    {
      "name": "python-gdbm",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    },
    {
      "name": "python-idle",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    },
    {
      "name": "python-tk",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    },
    {
      "name": "python-x86",
      "status": "released",
      "fixed_version": "0:2.6.0-8.12.2",
      "platform": "SUSE Linux Enterprise Server 11 SP2"
    }
  ],
  "references": [
    {
      "id": "Mitre CVE-2008-3143",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-3143"
    },
    {
      "id": "SUSE CVE-2008-3143",
      "source": "SUSE CVE",
      "url": "https://www.suse.com/security/cve/CVE-2008-3143"
    },
    {
      "id": "SUSE-SR:2008:017",
      "source": "SUSE-SU",
      "url": "https://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html"
    },
    {
      "id": "SUSE-SU-2020:0234-1",
      "source": "SUSE-SU",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2020-January/006406.html"
    },
    {
      "id": "SUSE bug 406051",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/406051"
    },
    {
      "id": "SUSE bug 444989",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/444989"
    },
    {
      "id": "SUSE bug 609759",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/609759"
    }
  ],
  "issued": "2021-04-30T00:00:00Z",
  "updated": "2022-04-21T00:00:00Z"
}
