{
  "id": "CVE-2018-14624",
  "definition_id": "oval:com.ubuntu.groovy:def:2018146240000000",
  "title": "CVE-2018-14624 on Ubuntu 20.10 (groovy) - medium.",
  "description": "A vulnerability was discovered in 389-ds-base through versions 1.3.7.10, 1.3.8.8 and 1.4.0.16. The lock controlling the error log was not correctly used when re-opening the log file in log__error_emergency(). An attacker could send a flood of modifications to a very large DN, which would cause slapd to crash.",
  "note": "",
  "severity": "Medium",
  "affected": {
    "family": "unix",
    "platform": "Ubuntu 20.10"
  },
  "packages": [
    {
      "name": "389-ds-base",
      "status": "not-affected",
      "note": "1.4.0.18-1"
    }
  ],
  "references": [
    {
      "id": "CVE-2018-14624",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-14624"
    },
    {
      "id": "",
      "source": "REF",
      "url": "http://people.canonical.com/~ubuntu-security/cve/2018/CVE-2018-14624.html"
    },
    {
      "id": "",
      "source": "BUG",
      "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907778"
    }
  ],
  "public_date": "2018-09-06T14:29:00Z",
  "rights": "Copyright (C) 2018 Canonical Ltd."
}
