{
  "candidate": "CVE-2022-34265",
  "description": "An issue was discovered in Django 3.2 before 3.2.14 and 4.0 before 4.0.6. The Trunc() and Extract() database functions are subject to SQL injection if untrusted data is used as a kind/lookup_name value. Applications that constrain the lookup name and kind choice to a known safe list are unaffected.",
  "notes": {
    "amurray": "original advisory only lists 3.2.x and 4.x as affected but looks like 1.11.x as used in bionic and 2.2.x as used in focal/impish are also likely vulnerable too"
  },
  "priority": "medium",
  "cvss": {
    "nvd": {
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "score": 9.8,
      "severity": "CRITICAL"
    }
  },
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-34265",
    "https://ubuntu.com/security/notices/USN-5501-1"
  ],
  "assigned_to": "leosilva",
  "public_date": "2022-07-04T16:15:00Z",
  "public_date_at_usn": "2022-07-04T08:00:00Z",
  "crd": "2022-07-04T08:00:00Z",
  "packages": [
    {
      "name": "python-django",
      "status": "released",
      "note": "2:2.2.24-1ubuntu1.5"
    }
  ]
}
