{
  "id": "CVE-2015-0221",
  "dsa_id": "DSA-3151",
  "definition_id": "oval:org.debian:def:235973493509328070971090920043152494485",
  "title": "DSA-3151-1 python-django",
  "description": "security update",
  "moreinfo": "\nSeveral vulnerabilities were discovered in Django, a high-level Python web development framework. The Common Vulnerabilities and Exposures project identifies the following problems:",
  "affected": {
    "family": "unix",
    "platform": "Debian GNU/Linux 8",
    "product": "python-django"
  },
  "package": {
    "name": "python-django",
    "fixed_version": "0:1.7.1-1.1"
  },
  "date": "2015-02-03T00:00:00Z",
  "references": [
    {
      "id": "CVE-2015-0219",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-0219"
    },
    {
      "id": "CVE-2015-0220",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-0220"
    },
    {
      "id": "CVE-2015-0221",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-0221"
    }
  ]
}
